import { listExpenses, listInvoices, listJobs } from "./desktop";

type DailyReportSettings={enabled:boolean;recipient:string;sendTime:string;serviceId?:string;templateId?:string;publicKey?:string};
export const defaultDailyReportSettings={serviceId:"service_rxuyna6",templateId:"template_hy6e8vi",publicKey:"mvJ716sG3Lc0UiHJL"};
const key="printmanager.daily-report";
export const getDailyReportSettings=():DailyReportSettings=>{try{return {...defaultDailyReportSettings,...(JSON.parse(localStorage.getItem(key)||"null")||{}),enabled:JSON.parse(localStorage.getItem(key)||"null")?.enabled??false,recipient:JSON.parse(localStorage.getItem(key)||"null")?.recipient||"",sendTime:JSON.parse(localStorage.getItem(key)||"null")?.sendTime||"18:00"}}catch{return{...defaultDailyReportSettings,enabled:false,recipient:"",sendTime:"18:00"}}};
const money=(value:number)=>`UGX ${Math.round(value).toLocaleString("en-UG")}`;
export async function sendDailyReport(settings:DailyReportSettings){if(!settings.serviceId||!settings.templateId||!settings.publicKey)throw new Error("Add the EmailJS service, template and public key in Settings first.");const [invoices,jobs,expenses]=await Promise.all([listInvoices(),listJobs(""),listExpenses("")]);const today=new Date().toISOString().slice(0,10);const todayInvoices=invoices.filter(item=>(item.issueDate||"").slice(0,10)===today);const todayJobs=jobs.filter(item=>(item.createdAt||"").slice(0,10)===today);const todayExpenses=expenses.filter(item=>(item.expenseDate||"").slice(0,10)===today);const collected=todayInvoices.reduce((sum,item)=>sum+item.amountPaid,0);const billed=todayJobs.reduce((sum,item)=>sum+item.totalAmount,0);const spent=todayExpenses.reduce((sum,item)=>sum+item.amount,0);const unpaid=todayJobs.reduce((sum,job)=>sum+Math.max(0,job.totalAmount-job.depositAmount),0);const templateParams={to_email:settings.recipient,report_date:today,total_collected:money(collected),total_billed:money(billed),total_expenses:money(spent),total_unpaid:money(unpaid),jobs_count:String(todayJobs.length),invoices_count:String(todayInvoices.length),summary:`Collected ${money(collected)} · Expenses ${money(spent)} · Unpaid ${money(unpaid)} · ${todayJobs.length} jobs`};const response=await fetch("https://api.emailjs.com/api/v1.0/email/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service_id:settings.serviceId,template_id:settings.templateId,user_id:settings.publicKey,template_params:templateParams})});if(!response.ok)throw new Error(`EmailJS returned ${response.status}`);localStorage.setItem("printmanager.daily-report-last-sent",today);}
export async function checkDailyReport(){const settings=getDailyReportSettings();if(!settings.enabled||!settings.recipient||localStorage.getItem("printmanager.daily-report-last-sent")===new Date().toISOString().slice(0,10))return;const now=new Date();if(now.toTimeString().slice(0,5)<settings.sendTime)return;await sendDailyReport(settings);}
