import { useEffect, useState } from "react";
import { ArrowRight, Banknote, BriefcaseBusiness, CalendarClock, CircleDollarSign, Equal, Minus, ReceiptText, ShoppingCart, WalletCards } from "lucide-react";
import { BusinessProfile, DashboardSummary, getDashboardSummary, listExpenses, listJobs, listPurchases } from "./lib/desktop";
import { productionStages } from "./JobsPage";
import { notifyActivity } from "./lib/activity";

const emptySummary: DashboardSummary = { salesToday: 0, salesMonth: 0, expensesToday: 0, expensesMonth: 0, netCashMonth: 0, outstanding: 0, activeJobs: 0, jobsDueToday: 0, overdueJobs: 0, completedJobs: 0, recentJobs: [] };
const money = (value: number) => new Intl.NumberFormat("en-UG", { style: "currency", currency: "UGX", maximumFractionDigits: 0 }).format(value);
const stage = (value: string) => productionStages.find(([key]) => key === value)?.[1] ?? value;

export default function DashboardPage({ profile, userName, onNavigate }: { profile: BusinessProfile; userName?: string; onNavigate: (page: string) => void }) {
  const [summary, setSummary] = useState(emptySummary); const [loading, setLoading] = useState(true);
  const [loadError,setLoadError]=useState("");
  const [savingsRate,setSavingsRate]=useState(()=>Number(JSON.parse(localStorage.getItem("printmanager.accounting-rules")||"null")?.savings??(localStorage.getItem("printmanager.savings-rate")||5)));
  const [savingsTarget,setSavingsTarget]=useState(()=>Number(localStorage.getItem("printmanager.monthly-savings-target")||1000000));
  const [period,setPeriod]=useState("today");const[customDate,setCustomDate]=useState("");const[periodJobsCount,setPeriodJobsCount]=useState(0);const[jobFinance,setJobFinance]=useState({collected:0,expenses:0,expensePaid:0,unpaid:0,supplierOwed:0,supplierBills:0,vendorOwed:0,vendorBills:0,anomaly:""});
  useEffect(() => { let disposed=false; const refreshPeriodTotals=async()=>{try{const jobs=await listJobs("");if(disposed)return;const range=dashboardRange(period,customDate);const periodJobs=period==="all"?jobs:range?jobs.filter(job=>{const day=localTimestampDate(job.createdAt);return day>=range.from&&day<=range.to}):[];setPeriodJobsCount(periodJobs.length);setJobFinance(previous=>({...previous,unpaid:periodJobs.reduce((sum,job)=>sum+Math.max(0,job.totalAmount-job.depositAmount),0)}));}catch{}};void refreshPeriodTotals();const timer=window.setInterval(()=>void refreshPeriodTotals(),1000);return()=>{disposed=true;window.clearInterval(timer)}; }, [period,customDate]);
  const load = async () => { setLoading(true);try {const range=dashboardRange(period,customDate);const [dashboard,jobs,expenses,purchases]=await Promise.all([getDashboardSummary(),listJobs(""),listExpenses(""),listPurchases()]);const periodJobs=period==="all"?jobs:range?jobs.filter(job=>{const day=localTimestampDate(job.createdAt);return day>=range.from&&day<=range.to}):[];const periodExpenses=period==="all"?expenses:range?expenses.filter(expense=>{const day=expense.expenseDate?.trim().slice(0,10)||"";return day>=range.from&&day<=range.to}):[];const supplierOwed=purchases.reduce((sum,purchase)=>sum+Math.max(0,purchase.total-(purchase.amountPaid??(purchase.paymentStatus==="paid"?purchase.total:0))),0);const vendorExpenses=expenses.filter(expense=>!expense.purchaseId);const vendorOwed=vendorExpenses.reduce((sum,expense)=>sum+Math.max(0,expense.amount-(expense.amountPaid??(expense.paymentStatus==="paid"?expense.amount:0))),0);const largest=periodExpenses.reduce((best,item)=>item.amount>best.amount?item:best,{amount:0,description:""} as {amount:number;description:string});const totalPeriodExpense=periodExpenses.reduce((sum,item)=>sum+item.amount,0);const anomaly=largest.amount>0&&totalPeriodExpense>0&&largest.amount/totalPeriodExpense>=.5?`${largest.description||"One expense"} represents ${Math.round(largest.amount/totalPeriodExpense*100)}% of this period’s spending.`:"";setSummary(dashboard);setJobFinance({collected:periodJobs.reduce((sum,job)=>sum+job.depositAmount,0),expenses:totalPeriodExpense,expensePaid:periodExpenses.reduce((sum,expense)=>sum+(expense.amountPaid??(expense.paymentStatus==="paid"?expense.amount:0)),0),unpaid:jobs.reduce((sum,job)=>sum+Math.max(0,job.totalAmount-job.depositAmount),0),supplierOwed,supplierBills:purchases.filter(purchase=>purchase.paymentStatus!=="paid").length,vendorOwed,vendorBills:vendorExpenses.filter(expense=>expense.paymentStatus!=="paid").length,anomaly});setLoadError("")}catch(reason){setLoadError(String(reason))}finally { setLoading(false); } };
  useEffect(() => { void load(); const refresh = () => void load();const interval=window.setInterval(refresh,5000);window.addEventListener("focus", refresh);window.addEventListener("printmanager:data-changed",refresh); return () => {clearInterval(interval);window.removeEventListener("focus", refresh);window.removeEventListener("printmanager:data-changed",refresh)}; }, [period,customDate]);
  const periodLabel=period==="all"?"for all time":period==="today"?"today":period==="yesterday"?"yesterday":period==="7days"?"in the last 7 days":period==="3months"?"in the last 3 months":customDate?`on ${new Intl.DateTimeFormat("en-UG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${customDate}T12:00:00`))}`:"for selected date";
  const firstName = (userName || profile.ownerName).split(" ")[0] || "there"; const date = new Intl.DateTimeFormat("en-UG", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date());const hour=new Date().getHours();const greeting=hour<12?"Good morning":hour<17?"Good afternoon":"Good evening";
  const collected=jobFinance.collected; const expensePaid=jobFinance.expensePaid; const rules=(()=>{try{return JSON.parse(localStorage.getItem("printmanager.accounting-rules")||"null")||{operating:50,materials:20,salaries:15,tax:10,savings:savingsRate}}catch{return {operating:50,materials:20,salaries:15,tax:10,savings:savingsRate}}})(); const savings=Math.max(0,collected)*Math.min(100,Math.max(0,Number(rules.savings)||0))/100; const remaining=collected-expensePaid-savings; const collectionPct=jobFinance.expenses>0?Math.round((collected/jobFinance.expenses)*100):collected>0?100:0; const health=Math.max(0,Math.min(100,Math.round(60+(collectionPct>=100?20:-10)-(jobFinance.unpaid>collected?15:0)-(jobFinance.supplierOwed>collected?10:0))));
  const updateSavingsRate=(value:number)=>{const next=Math.min(100,Math.max(0,Number.isFinite(value)?value:0));setSavingsRate(next);localStorage.setItem("printmanager.savings-rate",String(next));};
  const updateSavingsTarget=(value:number)=>{const next=Math.max(0,Number.isFinite(value)?value:0);setSavingsTarget(next);localStorage.setItem("printmanager.monthly-savings-target",String(next));};
  const forecastAvailable=Math.max(0,remaining)+jobFinance.unpaid; const projectedNet=forecastAvailable-(jobFinance.supplierOwed+jobFinance.vendorOwed); const monthSavings=Math.max(0,summary.salesMonth)*Number(rules.savings||0)/100; const savingsProgress=savingsTarget>0?Math.min(100,Math.round(monthSavings/savingsTarget*100)):0; const alerts=[...(jobFinance.anomaly?[`Unusual spending detected: ${jobFinance.anomaly}`]:[]),...(remaining<0?["Paid expenses are higher than this period’s collections."]:[]),...(jobFinance.unpaid>collected&&jobFinance.unpaid>0?["Unpaid customer jobs exceed current collections."]:[]),...(jobFinance.supplierOwed+jobFinance.vendorOwed>collected&&collected>0?["Supplier and vendor balances exceed current collections."]:[])];
  useEffect(()=>{if(!alerts.length)return;const day=dashboardDateKey(new Date());const signature=alerts.join("|");const key=`printmanager.alerts.${day}`;const sent=JSON.parse(localStorage.getItem(key)||"[]") as string[];if(!sent.includes(signature)){notifyActivity({title:"Accounting alert",detail:alerts[0],page:"Dashboard",tone:"warning"});localStorage.setItem(key,JSON.stringify([...sent,signature]));}},[alerts.join("|")]);
  return <><section className="page-heading"><div><p className="eyebrow">{date}</p><h1>{greeting}, {firstName}.</h1><p>Live information from {profile.businessName}’s local database.</p></div><button className="secondary-button" onClick={() => onNavigate("Sales")}><ReceiptText size={18} /> View sales</button></section>
    <section className={`live-banner ${loadError?"sync-error":""}`}><span /><div><strong>{loadError?"Dashboard could not refresh":"Business database connected"}</strong><p>{loading ? "Reading your business records…" : loadError||"Financial totals refresh automatically every 5 seconds."}</p></div><button onClick={() => void load()}>Refresh</button></section>
    <section className="dashboard-period-bar"><div><CalendarClock/><span><strong>Dashboard period</strong><small>Financial cards refresh automatically</small></span></div><select value={period} onChange={event=>setPeriod(event.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7days">Last 7 days</option><option value="3months">Last 3 months</option><option value="all">All time</option><option value="custom">Custom date…</option></select>{period==="custom"&&<input type="date" value={customDate} onChange={event=>setCustomDate(event.target.value)}/>}</section>
    <section className="metrics-grid live-metrics"><article><span><CircleDollarSign size={19} /></span><small>Total money collected {periodLabel}</small><strong>{money(jobFinance.collected)}</strong></article><article><span><ReceiptText size={19} /></span><small>Expenses {periodLabel}</small><strong>{money(jobFinance.expenses)}</strong></article><article><span><WalletCards size={19} /></span><small>Total unpaid on jobs {periodLabel}</small><strong>{money(jobFinance.unpaid)}</strong></article><article><span><BriefcaseBusiness size={19} /></span><small>Total print jobs {periodLabel}</small><strong>{periodJobsCount}</strong></article></section>
    <section className={`cash-position ${jobFinance.collected-jobFinance.expensePaid<0?"negative":""}`}><header><span><Banknote/></span><div><small>CASH POSITION</small><h2>Money remaining {periodLabel}</h2><p>Actual job payments received minus expenses already paid.</p></div></header><div className="cash-equation"><article><small>Collected</small><strong>{money(jobFinance.collected)}</strong></article><Minus/><article><small>Expenses paid</small><strong>{money(jobFinance.expensePaid)}</strong><em>{money(Math.max(0,jobFinance.expenses-jobFinance.expensePaid))} still payable</em></article><Equal/><article className="cash-balance"><small>Money remaining</small><strong>{money(jobFinance.collected-jobFinance.expensePaid)}</strong><em>{jobFinance.collected-jobFinance.expensePaid>=0?"Available after recorded payments":"Expenses paid exceed collections"}</em></article></div></section>
    <section className="accounting-assistant"><header><div><small>ACCOUNTING ASSISTANT</small><h2>Today’s financial guidance</h2><p>Based on your jobs, expenses, collections and outstanding balances.</p></div><label>Save <input type="number" min="0" max="100" step="1" value={rules.savings} onChange={event=>updateSavingsRate(Number(event.target.value))}/> %</label></header><div className="assistant-grid"><article><small>Collection coverage</small><strong>{collectionPct}%</strong><span>collections compared with recorded expenses</span></article><article><small>Recommended savings</small><strong>{money(savings)}</strong><span>{rules.savings}% of today’s collection</span></article><article><small>After reserves</small><strong>{money(remaining)}</strong><span>cash after paid expenses and savings</span></article><article><small>Financial health</small><strong>{health}/100</strong><span>{health>=75?"Healthy position":"Needs attention"}</span></article></div><div className="allocation-breakdown">{[["Operating expenses","operating"],["Materials reserve","materials"],["Salaries","salaries"],["Tax reserve","tax"],["Business savings","savings"]].map(([label,key])=><span key={key}><small>{label} · {rules[key]}%</small><strong>{money(collected*Number(rules[key]||0)/100)}</strong></span>)}</div><div className="cash-forecast"><div><small>30-DAY CASH FLOW FORECAST</small><strong>{money(projectedNet)}</strong><span>Projected after unpaid jobs and supplier/vendor balances</span></div><i className={projectedNet<0?"forecast-negative":"forecast-positive"}>{projectedNet<0?"Review obligations":"Positive outlook"}</i></div><div className="savings-progress"><div><span><small>Monthly savings target</small><strong>{money(monthSavings)} of {money(savingsTarget)}</strong></span><label>Target <input type="number" min="0" step="10000" value={savingsTarget} onChange={event=>updateSavingsTarget(Number(event.target.value))}/></label></div><i><b style={{width:`${savingsProgress}%`}}/></i><small>{savingsProgress}% complete from monthly collections</small></div>{alerts.length>0&&<div className="finance-alerts">{alerts.map(alert=><p key={alert}>⚠ {alert}</p>)}</div>}<div className="assistant-insight"><span>?</span><div><strong>Assistant insight</strong><p>{collected===0?"No collections have been recorded for this period yet.":collectionPct>=100?`Collections are covering ${collectionPct}% of recorded expenses. Keep ${money(savings)} aside for your savings target.`:`Collections currently cover ${collectionPct}% of recorded expenses. Review unpaid jobs and protect your operating cash.`}</p></div></div><p className="assistant-note">You collected {money(collected)} {periodLabel}. Set aside {money(savings)} for savings, then review {money(jobFinance.unpaid)} in unpaid job balances and {money(jobFinance.supplierOwed+jobFinance.vendorOwed)} owed to suppliers and vendors.</p></section>
    <section className="dashboard-supplier-payable"><span><ShoppingCart/></span><div><small>ACCOUNTS PAYABLE</small><h2>Business money owed</h2><p>{jobFinance.supplierBills} supplier bills · {jobFinance.vendorBills} other vendor bills</p></div><strong>{money(jobFinance.supplierOwed+jobFinance.vendorOwed)}<small>{money(jobFinance.supplierOwed)} suppliers · {money(jobFinance.vendorOwed)} others</small></strong><button onClick={()=>onNavigate("Expenses")}>View payables <ArrowRight/></button></section>
    <section className="dashboard-grid live-dashboard"><div className="panel"><div className="panel-head"><div><h2>Recent print jobs</h2><p>Current records ordered by priority and deadline</p></div><button onClick={() => onNavigate("Jobs")}>View jobs <ArrowRight size={16} /></button></div>{summary.recentJobs.length === 0 ? <div className="live-empty"><BriefcaseBusiness size={25} /><strong>No print jobs yet</strong><p>Create a job or convert an accepted quotation.</p><button onClick={() => onNavigate("Jobs")}>Open print jobs</button></div> : <div className="live-job-list">{summary.recentJobs.map(job => <button key={job.id} onClick={() => onNavigate("Jobs")}><span><strong>{job.jobNumber}</strong><small>{job.title}</small></span><span>{job.customerName || "Walk-in customer"}</span><i>{stage(job.status)}</i><span>{job.deadline || "No deadline"}</span><strong>{money(job.totalAmount)}</strong></button>)}</div>}</div><div className="panel dashboard-attention"><div className="panel-head"><div><h2>Production attention</h2><p>Based on current deadlines</p></div></div><div><span className="attention-number amber">{summary.jobsDueToday}</span><p><strong>Due today</strong><small>Active jobs with today’s deadline</small></p></div><div><span className="attention-number red">{summary.overdueJobs}</span><p><strong>Overdue</strong><small>Jobs requiring immediate attention</small></p></div><div><span className="attention-number green">{summary.completedJobs}</span><p><strong>Delivered</strong><small>Completed jobs in the database</small></p></div><button onClick={() => onNavigate("Production")}>Open production board <ArrowRight size={15} /></button></div></section>
    <section className="dashboard-shortcuts"><button onClick={() => onNavigate("Sales")}><CircleDollarSign /><span><strong>Record a sale</strong><small>Create an invoice and collect payment</small></span><ArrowRight /></button><button onClick={() => onNavigate("Quotations")}><ReceiptText /><span><strong>Create quotation</strong><small>Price a customer’s print work</small></span><ArrowRight /></button><button onClick={() => onNavigate("Production")}><CalendarClock /><span><strong>Review production</strong><small>Move active jobs through the workshop</small></span><ArrowRight /></button></section>
  </>;
}

function localTimestampDate(value:string|null|undefined){if(!value)return "";if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const normalized=value.includes(" ")&&!value.includes("T")?value.replace(" ","T"):value;const parsed=new Date(/Z$|[+-]\d\d:?\d\d$/.test(normalized)?normalized:`${normalized}Z`);return Number.isNaN(parsed.getTime())?value.slice(0,10):dashboardDateKey(parsed)}
function dashboardDateKey(date:Date){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,10)}
function dashboardRange(period:string,custom:string){const now=new Date();const today=dashboardDateKey(now);if(period==="today")return{from:today,to:today};if(period==="custom")return custom?{from:custom,to:custom}:null;const start=new Date(now);if(period==="yesterday"){start.setDate(start.getDate()-1);const day=dashboardDateKey(start);return{from:day,to:day}}if(period==="7days")start.setDate(start.getDate()-6);else start.setMonth(start.getMonth()-3);return{from:dashboardDateKey(start),to:today}}








