import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Cog, Plus, Printer, Trash2, Truck, X } from "lucide-react";
import { Job, Machine, deleteRecord, listJobs, listMachines, saveJob, saveMachine } from "./lib/desktop";
import { notifyActivity } from "./lib/activity";
import DeleteConfirm from "./DeleteConfirm";

const blankMachine = (): Machine => ({ name: "", machineType: "", model: "", status: "available", notes: "", isActive: true });
const machineStatuses: Record<string, string> = { available: "Available", in_use: "In use", maintenance: "Maintenance", out_of_service: "Out of service" };
const artworkStatuses = ["not_received", "received", "proof_sent", "changes_requested", "approved"];

export default function WorkshopPage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [machines, setMachines] = useState<Machine[]>([]); const [editing, setEditing] = useState<Machine | null>(null); const [error, setError] = useState("");const[deleting,setDeleting]=useState<Machine|null>(null);const[deleteError,setDeleteError]=useState("");const[deletingBusy,setDeletingBusy]=useState(false);
  const load = async () => { const [jobList, machineList] = await Promise.all([listJobs(), listMachines()]); setJobs(jobList); setMachines(machineList); };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; setError(""); try { const wasEditing=!!editing.id; const saved=await saveMachine(editing); notifyActivity({title:`Machine ${wasEditing?"updated":"registered"}`,detail:`${saved.name} · ${machineStatuses[saved.status]||saved.status}`,page:"Workshop",tone:"info"}); setEditing(null); await load(); } catch (reason) { setError(String(reason)); } };
  const updateArtwork = async (job: Job, artworkStatus: string) => { const updated = await saveJob({ ...job, artworkStatus }); notifyActivity({title:"Artwork status updated",detail:`${job.jobNumber||job.title} · ${artworkStatus.replaceAll("_"," ")}`,page:"Workshop",tone:"info"}); setJobs(current => current.map(item => item.id === job.id ? updated : item)); };
  const removeMachine=async()=>{if(!deleting?.id)return;setDeletingBusy(true);setDeleteError("");try{await deleteRecord("machine",deleting.id);notifyActivity({title:`${deleting.name} deleted`,detail:"The machine was removed permanently.",page:"Workshop",tone:"warning"});setDeleting(null);setEditing(null);await load()}catch(reason){setDeleteError(String(reason))}finally{setDeletingBusy(false)}};
  const schedule = useMemo(() => jobs.filter(job => job.deadline || job.deliveryDate).sort((a, b) => (a.deadline || a.deliveryDate || "").localeCompare(b.deadline || b.deliveryDate || "")), [jobs]);
  return <>
    <section className="list-heading"><div><p className="eyebrow">WORKSHOP CONTROL</p><h1>Machines & schedule</h1><p>Coordinate equipment, production deadlines, artwork approvals and deliveries.</p></div><button className="primary-button" onClick={() => setEditing(blankMachine())}><Plus /> Add machine</button></section>
    <section className="machine-grid">{machines.length === 0 ? <div className="workshop-empty"><Printer /><strong>No machines registered</strong><p>Add printers, cutters, laminators and finishing equipment.</p></div> : machines.map(machine => <button key={machine.id} onClick={() => setEditing(machine)}><span><Printer /></span><div><strong>{machine.name}</strong><small>{machine.machineType || "Printing equipment"}{machine.model ? ` • ${machine.model}` : ""}</small></div><i className={machine.status}>{machineStatuses[machine.status] || machine.status}</i></button>)}</section>
    <section className="schedule-panel"><header><div><CalendarDays /><span><h2>Production calendar</h2><p>Upcoming deadlines and customer handovers</p></span></div><strong>{schedule.length} scheduled</strong></header>{schedule.length === 0 ? <div className="workshop-empty"><CalendarDays /><strong>No work scheduled</strong><p>Add deadlines or delivery dates to print jobs.</p></div> : <div className="schedule-list">{schedule.map(job => { const art = job.artworkStatus || "not_received"; const delivery = job.deliveryMethod || "collection"; return <article key={job.id}><time>{job.deadline || job.deliveryDate}</time><div><strong>{job.jobNumber} • {job.title}</strong><small>{job.customerName || "Walk-in customer"}{job.machineName ? ` • ${job.machineName}` : ""}</small></div><label className={`art-${art}`}>{art === "approved" ? <CheckCircle2 /> : <Cog />}<select value={art} onChange={event => void updateArtwork(job, event.target.value)}>{artworkStatuses.map(status => <option value={status} key={status}>{status.replaceAll("_", " ")}</option>)}</select></label><em>{delivery === "delivery" ? <Truck /> : <CalendarDays />}{delivery}</em></article>; })}</div>}</section>
    {editing && <div className="modal-backdrop"><form className="customer-modal" onSubmit={submit}><div className="modal-head"><div><span><Printer /></span><div><h2>{editing.id ? "Edit machine" : "New machine"}</h2><p>Workshop equipment record</p></div></div><button type="button" onClick={() => setEditing(null)}><X /></button></div><div className="modal-body"><label>Machine name<input required autoFocus value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} placeholder="e.g. Epson SureColor S80600" /></label><div className="form-row"><label>Machine type<input value={editing.machineType} onChange={event => setEditing({ ...editing, machineType: event.target.value })} placeholder="Large format printer" /></label><label>Model<input value={editing.model} onChange={event => setEditing({ ...editing, model: event.target.value })} /></label></div><label>Status<select value={editing.status} onChange={event => setEditing({ ...editing, status: event.target.value })}>{Object.entries(machineStatuses).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Notes<textarea rows={3} value={editing.notes} onChange={event => setEditing({ ...editing, notes: event.target.value })} /></label><label className="active-toggle"><input type="checkbox" checked={editing.isActive} onChange={event => setEditing({ ...editing, isActive: event.target.checked })} /><span><i>✓</i><strong>Machine is active</strong><small>Available for job assignment.</small></span></label>{error && <p className="setup-error">{error}</p>}</div><div className="modal-actions"><button type="button" className="setup-back" onClick={() => setEditing(null)}>Cancel</button><button className="setup-next">Save machine</button></div></form></div>}
    {editing?.id&&<button className="floating-record-delete" onClick={()=>setDeleting(editing)}><Trash2/> Delete machine</button>}
    {deleting&&<DeleteConfirm name={deleting.name} kind="machine" busy={deletingBusy} error={deleteError} onCancel={()=>setDeleting(null)} onConfirm={()=>void removeMachine()}/>} 
  </>;
}
